# GRAVE_ESC 활성화
GRAVE_ESC_ALT_OVERRIDE = yes
GRAVE_ESC_CTRL_OVERRIDE = yes
GRAVE_ESC_GUI_OVERRIDE = yes
GRAVE_ESC_SHIFT_OVERRIDE = yes

# COMBO_ENABLE = yes
# TAP_DANCE_ENABLE = yes

BOOTMAGIC_ENABLE = yes
